// <auto-generated />
using System;
using IoBuild.Projects.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoBuild.Projects.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618180117_AddUnitStructureAndOwnerLinking")]
    partial class AddUnitStructureAndOwnerLinking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IoBuild.Projects.Domain.Model.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountStatement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("account_statement");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("project_name");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountStatement = "Active",
                            Address = "Av. Arequipa 1450, Lince, Lima",
                            Email = "carlos.mendoza@email.com",
                            FullName = "Carlos Mendoza Ruiz",
                            PhoneNumber = "+51 998765432",
                            ProjectId = 1,
                            ProjectName = "Residencial Los Álamos"
                        },
                        new
                        {
                            Id = 2,
                            AccountStatement = "Active",
                            Address = "Calle Los Olivos 234, San Isidro, Lima",
                            Email = "ana.torres@email.com",
                            FullName = "Ana Lucía Torres",
                            PhoneNumber = "+51 987654321",
                            ProjectId = 1,
                            ProjectName = "Residencial Los Álamos"
                        },
                        new
                        {
                            Id = 3,
                            AccountStatement = "Pending",
                            Address = "Jr. Monterrey 567, La Molina, Lima",
                            Email = "roberto.vargas@email.com",
                            FullName = "Roberto Vargas León",
                            PhoneNumber = "+51 976543210",
                            ProjectId = 1,
                            ProjectName = "Residencial Los Álamos"
                        },
                        new
                        {
                            Id = 4,
                            AccountStatement = "Active",
                            Address = "Av. Benavides 2890, Miraflores, Lima",
                            Email = "patricia.salazar@email.com",
                            FullName = "Patricia Salazar Gómez",
                            PhoneNumber = "+51 965432109",
                            ProjectId = 1,
                            ProjectName = "Residencial Los Álamos"
                        },
                        new
                        {
                            Id = 5,
                            AccountStatement = "Suspended",
                            Address = "Calle San Martín 890, Barranco, Lima",
                            Email = "luis.rojas@email.com",
                            FullName = "Luis Fernando Rojas",
                            PhoneNumber = "+51 954321098",
                            ProjectId = 1,
                            ProjectName = "Residencial Los Álamos"
                        },
                        new
                        {
                            Id = 6,
                            AccountStatement = "Active",
                            Address = "Malecón Cisneros 1234, Miraflores, Lima",
                            Email = "sandra.valverde@email.com",
                            FullName = "Sandra Valverde Castro",
                            PhoneNumber = "+51 943210987",
                            ProjectId = 2,
                            ProjectName = "Torres del Pacífico"
                        },
                        new
                        {
                            Id = 7,
                            AccountStatement = "Active",
                            Address = "Av. Larco 789, Miraflores, Lima",
                            Email = "miguel.herrera@email.com",
                            FullName = "Miguel Ángel Herrera",
                            PhoneNumber = "+51 932109876",
                            ProjectId = 2,
                            ProjectName = "Torres del Pacífico"
                        },
                        new
                        {
                            Id = 8,
                            AccountStatement = "Active",
                            Address = "Calle Shell 456, Miraflores, Lima",
                            Email = "gabriela.quispe@email.com",
                            FullName = "Gabriela Quispe Flores",
                            PhoneNumber = "+51 921098765",
                            ProjectId = 2,
                            ProjectName = "Torres del Pacífico"
                        },
                        new
                        {
                            Id = 9,
                            AccountStatement = "Inactive",
                            Address = "Av. Angamos 2345, Surquillo, Lima",
                            Email = "fernando.diaz@email.com",
                            FullName = "Fernando Díaz Pérez",
                            PhoneNumber = "+51 910987654",
                            ProjectId = 2,
                            ProjectName = "Torres del Pacífico"
                        },
                        new
                        {
                            Id = 10,
                            AccountStatement = "Pending",
                            Address = "Av. Javier Prado Este 4567, Surco, Lima",
                            Email = "maria.vega@email.com",
                            FullName = "María Elena Vega",
                            PhoneNumber = "+51 909876543",
                            ProjectId = 3,
                            ProjectName = "Condominio Las Casuarinas"
                        },
                        new
                        {
                            Id = 11,
                            AccountStatement = "Pending",
                            Address = "Calle Las Camelias 345, San Isidro, Lima",
                            Email = "jorge.campos@email.com",
                            FullName = "Jorge Luis Campos",
                            PhoneNumber = "+51 998876543",
                            ProjectId = 3,
                            ProjectName = "Condominio Las Casuarinas"
                        },
                        new
                        {
                            Id = 12,
                            AccountStatement = "Active",
                            Address = "Av. Primavera 890, Surco, Lima",
                            Email = "roxana.gutierrez@email.com",
                            FullName = "Roxana Gutiérrez Silva",
                            PhoneNumber = "+51 987765432",
                            ProjectId = 3,
                            ProjectName = "Condominio Las Casuarinas"
                        },
                        new
                        {
                            Id = 13,
                            AccountStatement = "Pending",
                            Address = "Calle Los Eucaliptos 123, Surco, Lima",
                            Email = "alberto.sanchez@email.com",
                            FullName = "Alberto Sánchez Torres",
                            PhoneNumber = "+51 976654321",
                            ProjectId = 3,
                            ProjectName = "Condominio Las Casuarinas"
                        },
                        new
                        {
                            Id = 14,
                            AccountStatement = "Active",
                            Address = "Av. Aviación 4321, San Borja, Lima",
                            Email = "elena.ramirez@email.com",
                            FullName = "Elena Ramírez Meza",
                            PhoneNumber = "+51 965543210",
                            ProjectId = 3,
                            ProjectName = "Condominio Las Casuarinas"
                        });
                });

            modelBuilder.Entity("IoBuild.Projects.Domain.Model.Aggregates.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuilderId")
                        .HasColumnType("int")
                        .HasColumnName("builder_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OccupiedUnits")
                        .HasColumnType("int")
                        .HasColumnName("occupied_units");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int")
                        .HasColumnName("total_units");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuilderId = 1,
                            CreatedDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complejo residencial de lujo con 120 departamentos en San Isidro. Cuenta con áreas verdes, piscina, gimnasio y vigilancia 24/7.",
                            ImageUrl = "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
                            Location = "Av. Conquistadores 890, San Isidro, Lima",
                            Name = "Residencial Los Álamos",
                            OccupiedUnits = 95,
                            Status = "OnGoing",
                            TotalUnits = 120
                        },
                        new
                        {
                            Id = 2,
                            BuilderId = 1,
                            CreatedDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Desarrollo de dos torres con vista al mar en Miraflores. 80 departamentos premium con acabados de primera calidad.",
                            ImageUrl = "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
                            Location = "Malecón de la Reserva 456, Miraflores, Lima",
                            Name = "Torres del Pacífico",
                            OccupiedUnits = 68,
                            Status = "OnGoing",
                            TotalUnits = 80
                        },
                        new
                        {
                            Id = 3,
                            BuilderId = 1,
                            CreatedDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Proyecto residencial en construcción con 60 departamentos tipo loft en Surco. Entrega prevista para Q2 2025.",
                            ImageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
                            Location = "Av. Primavera 1234, Santiago de Surco, Lima",
                            Name = "Condominio Las Casuarinas",
                            OccupiedUnits = 12,
                            Status = "OnGoing",
                            TotalUnits = 60
                        });
                });

            modelBuilder.Entity("IoBuild.Projects.Domain.Model.Aggregates.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("owner_email");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("room_number");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit_number");

                    b.HasKey("Id");

                    b.HasIndex("OwnerEmail");

                    b.HasIndex("ProjectId", "Floor", "RoomNumber")
                        .IsUnique();

                    b.ToTable("units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floor = 5,
                            OwnerId = 2,
                            ProjectId = 1,
                            RoomNumber = "01",
                            UnitNumber = "A-501"
                        },
                        new
                        {
                            Id = 2,
                            Floor = 5,
                            OwnerId = 2,
                            ProjectId = 1,
                            RoomNumber = "02",
                            UnitNumber = "A-502"
                        },
                        new
                        {
                            Id = 3,
                            Floor = 8,
                            OwnerId = 3,
                            ProjectId = 1,
                            RoomNumber = "01",
                            UnitNumber = "B-801"
                        },
                        new
                        {
                            Id = 4,
                            Floor = 12,
                            OwnerId = 4,
                            ProjectId = 2,
                            RoomNumber = "05",
                            UnitNumber = "T1-1205"
                        },
                        new
                        {
                            Id = 5,
                            Floor = 8,
                            OwnerId = 2,
                            ProjectId = 2,
                            RoomNumber = "01-T2",
                            UnitNumber = "T2-0801"
                        });
                });

            modelBuilder.Entity("IoBuild.Projects.Domain.Model.Entities.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("longtext")
                        .HasColumnName("error");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("IoBuild.Projects.Domain.Model.Entities.RegisteredOwner", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_event_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Email");

                    b.ToTable("registered_owner", (string)null);
                });

            modelBuilder.Entity("IoBuild.Projects.Domain.Model.Aggregates.Client", b =>
                {
                    b.HasOne("IoBuild.Projects.Domain.Model.Aggregates.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IoBuild.Projects.Domain.Model.Aggregates.Unit", b =>
                {
                    b.HasOne("IoBuild.Projects.Domain.Model.Aggregates.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
