using IoBuild.Projects.Application.Services;
using IoBuild.Projects.Domain.Services;
using IoBuild.Projects.Domain.Services.Commands.Projects;
using IoBuild.Projects.Domain.Services.Queries.Projects;
using IoBuild.Projects.Interfaces.Resources;
using IoBuild.Projects.Interfaces.Transform;
using IoBuild.Shared.Infrastructure.ASP.Configuration;
using Microsoft.AspNetCore.Mvc;

namespace IoBuild.Projects.Interfaces.REST;

[ApiController]
[Route("api/v1/projects")]
[Authorize]
public class ProjectsController : ControllerBase
{
    private readonly IProjectCommandService _commandService;
    private readonly IProjectQueryService _queryService;
    private readonly ProjectStructureCommandService _structureService;

    public ProjectsController(
        IProjectCommandService commandService,
        IProjectQueryService queryService,
        ProjectStructureCommandService structureService)
    {
        _commandService = commandService;
        _queryService = queryService;
        _structureService = structureService;
    }

    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        if (HttpContext.Items["UserId"] is int builderId)
        {
            var projects = await _queryService.Handle(new GetProjectsByBuilderIdQuery(builderId));
            return Ok(ProjectResourceFromEntityAssembler.ToResourceEnumerable(projects));
        }
        var all = await _queryService.Handle(new GetAllProjectsQuery());
        return Ok(ProjectResourceFromEntityAssembler.ToResourceEnumerable(all));
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetById(int id)
    {
        var project = await _queryService.Handle(new GetProjectByIdQuery(id));
        if (project == null)
            return NotFound();

        var resource = ProjectResourceFromEntityAssembler.ToResource(project);
        return Ok(resource);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromBody] CreateProjectResource resource)
    {
        var command = CreateProjectCommandFromResourceAssembler.ToCommand(resource);
        var id = await _commandService.Handle(command);
        var project = await _queryService.Handle(new GetProjectByIdQuery(id));
        var result = ProjectResourceFromEntityAssembler.ToResource(project!);
        return CreatedAtAction(nameof(GetById), new { id }, result);
    }

    [HttpPut("{id}")]
    public async Task<IActionResult> Update(int id, [FromBody] UpdateProjectResource resource)
    {
        var command = UpdateProjectCommandFromResourceAssembler.ToCommand(id, resource);
        await _commandService.Handle(command);
        return NoContent();
    }

    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(int id)
    {
        await _commandService.Handle(new DeleteProjectCommand(id));
        return NoContent();
    }

    /// <summary>
    /// POST /api/v1/projects/{id}/structure
    /// Defines the physical floor/room structure of a project (REQ-PS-01 / PS-S01).
    /// Requires the caller to have the Builder role (REQ-PS-06).
    /// Returns 200 on success, 409 if structure already defined (REQ-PS-03), 422 on validation error.
    /// </summary>
    [HttpPost("{id}/structure")]
    public async Task<IActionResult> DefineStructure(int id, [FromBody] DefineStructureResource resource)
    {
        // Builder-role guard (REQ-PS-06)
        var role = HttpContext.Items["UserRole"] as string;
        if (!string.Equals(role, "Builder", StringComparison.OrdinalIgnoreCase))
            return StatusCode(403, new { error = "Only users with the Builder role may define project structure." });

        var userId = HttpContext.Items["UserId"] is int uid ? uid : 0;

        // Expand uniform floors × unitsPerFloor into explicit FloorSpec/RoomSpec lists
        if (resource.Floors < 1)
            return UnprocessableEntity(new { error = "floors must be at least 1." });
        if (resource.UnitsPerFloor < 1)
            return UnprocessableEntity(new { error = "unitsPerFloor must be at least 1." });

        // SC-2.4: validate that floorDeviceTypes entries reference floors within [1, Floors].
        // Out-of-range floor numbers must return HTTP 400 (not be silently ignored).
        if (resource.DeviceTypesPerFloor is { Count: > 0 })
        {
            var outOfRange = resource.DeviceTypesPerFloor
                .Where(s => s.Floor < 1 || s.Floor > resource.Floors)
                .Select(s => s.Floor)
                .ToList();

            if (outOfRange.Count > 0)
                return BadRequest(new
                {
                    error = $"floorDeviceTypes references floor(s) out of range [1, {resource.Floors}]: " +
                            string.Join(", ", outOfRange) + "."
                });
        }

        // ADR-9 / T-10: validate that unitDevicePackages entries reference rooms that actually exist.
        // A room exists iff its roomNumber is in the set generated by Enumerable.Range(1, UnitsPerFloor)
        // formatted "D2", AND the floor is within [1, Floors].
        // Out-of-range references return HTTP 400, consistent with the SC-2.4 floor guard.
        if (resource.UnitDevicePackages is { Count: > 0 })
        {
            var validRoomNumbers = Enumerable.Range(1, resource.UnitsPerFloor)
                .Select(r => r.ToString("D2"))
                .ToHashSet(StringComparer.Ordinal);

            var invalidEntries = resource.UnitDevicePackages
                .Where(p => p.Floor < 1 || p.Floor > resource.Floors
                         || !validRoomNumbers.Contains(p.RoomNumber))
                .Select(p => $"floor={p.Floor}, room=\"{p.RoomNumber}\"")
                .ToList();

            if (invalidEntries.Count > 0)
                return BadRequest(new
                {
                    error = "unitDevicePackages references unit(s) that do not exist: " +
                            string.Join(", ", invalidEntries) + "."
                });
        }

        var floorSpecs = Enumerable.Range(1, resource.Floors)
            .Select(f =>
            {
                var rooms = Enumerable.Range(1, resource.UnitsPerFloor)
                    .Select(r =>
                    {
                        var roomNumber = r.ToString("D2");

                        // Look up optional per-unit owner email from the request
                        var email = resource.OwnerEmails?
                            .FirstOrDefault(oe => oe.Floor == f && oe.RoomNumber == roomNumber)
                            ?.Email;

                        // ADR-9 / T-10: look up optional per-unit device package.
                        // Mirrors the OwnerEmails FirstOrDefault lookup pattern.
                        var unitDeviceTypes = resource.UnitDevicePackages?
                            .FirstOrDefault(p => p.Floor == f && p.RoomNumber == roomNumber)
                            ?.DeviceTypes;

                        return new RoomSpec(
                            RoomNumber: roomNumber,
                            OwnerEmail: email,
                            DeviceTypes: unitDeviceTypes);
                    })
                    .ToList();

                // Look up optional per-floor device type selection (S2.1)
                // Mirrors the OwnerEmails FirstOrDefault lookup pattern above.
                var deviceTypes = resource.DeviceTypesPerFloor?
                    .FirstOrDefault(s => s.Floor == f)
                    ?.DeviceTypes;

                return new FloorSpec(Floor: f, Rooms: rooms, DeviceTypes: deviceTypes);
            })
            .ToList();

        var command = new DefineProjectStructureCommand(
            ProjectId: id,
            Floors: floorSpecs,
            BuilderId: userId);

        try
        {
            await _structureService.Handle(command);
        }
        catch (ArgumentException ex)
        {
            return UnprocessableEntity(new { error = ex.Message });
        }
        catch (InvalidOperationException ex)
        {
            return Conflict(new { error = ex.Message });
        }

        return StatusCode(201, new { message = $"Project structure defined: {resource.Floors} floor(s), {resource.UnitsPerFloor} unit(s) per floor." });
    }
}
