// <auto-generated />
using System;
using IoBuild.Devices.Infrastructure.Persistence.EFC.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoBuild.Devices.Migrations
{
    [DbContext(typeof(DevicesDbContext))]
    [Migration("20260703200256_RemoveOwnerCustomDeviceType")]
    partial class RemoveOwnerCustomDeviceType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IoBuild.Devices.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Source")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.Property<int>("UnitKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("unit_key")
                        .HasComputedColumnSql("COALESCE(unit_id, 0)", true);

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("ProjectId", "FloorNumber", "UnitKey", "Type")
                        .IsUnique()
                        .HasDatabaseName("IX_devices_project_id_floor_number_unit_key_type");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("IoBuild.Devices.Domain.Model.Aggregates.DeviceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("device_logs", (string)null);
                });

            modelBuilder.Entity("IoBuild.Devices.Domain.Model.Aggregates.DeviceShadow", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DesiredJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("desired_json");

                    b.Property<string>("ReportedJson")
                        .HasColumnType("longtext")
                        .HasColumnName("reported_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("DeviceId");

                    b.ToTable("device_shadows", (string)null);
                });

            modelBuilder.Entity("IoBuild.Devices.Domain.Model.Aggregates.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("attributes_json");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_device_types_code");

                    b.ToTable("device_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributesJson = "[]",
                            Code = "SmartMeter",
                            DisplayName = "Smart Meter",
                            Scope = "floor"
                        },
                        new
                        {
                            Id = 2,
                            AttributesJson = "[]",
                            Code = "WaterSensor",
                            DisplayName = "Water Sensor",
                            Scope = "floor"
                        },
                        new
                        {
                            Id = 3,
                            AttributesJson = "[]",
                            Code = "SmokeDetector",
                            DisplayName = "Smoke Detector",
                            Scope = "floor"
                        },
                        new
                        {
                            Id = 4,
                            AttributesJson = "[{\"Name\":\"targetTemperature\",\"Type\":\"number\",\"Min\":16.0,\"Max\":30.0,\"Unit\":\"C\",\"EnumMembers\":null},{\"Name\":\"mode\",\"Type\":\"enum\",\"Min\":null,\"Max\":null,\"Unit\":null,\"EnumMembers\":[\"cooling\",\"heating\",\"fan\"]},{\"Name\":\"power\",\"Type\":\"boolean\",\"Min\":null,\"Max\":null,\"Unit\":null,\"EnumMembers\":null}]",
                            Code = "AirConditioner",
                            DisplayName = "Air Conditioner",
                            Scope = "unit"
                        },
                        new
                        {
                            Id = 5,
                            AttributesJson = "[{\"Name\":\"brightness\",\"Type\":\"number\",\"Min\":0.0,\"Max\":100.0,\"Unit\":\"%\",\"EnumMembers\":null},{\"Name\":\"power\",\"Type\":\"boolean\",\"Min\":null,\"Max\":null,\"Unit\":null,\"EnumMembers\":null}]",
                            Code = "SmartLight",
                            DisplayName = "Smart Light",
                            Scope = "unit"
                        });
                });

            modelBuilder.Entity("IoBuild.Devices.Domain.Model.Aggregates.UnitOwnerProjection", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UnitId");

                    b.HasIndex("UnitId", "OwnerUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_unit_owner_projections_unit_id_owner_user_id");

                    b.ToTable("unit_owner_projections", (string)null);
                });

            modelBuilder.Entity("IoBuild.Devices.Domain.Model.Entities.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("longtext")
                        .HasColumnName("error");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("IoBuild.Devices.Domain.Model.Aggregates.DeviceShadow", b =>
                {
                    b.HasOne("IoBuild.Devices.Domain.Model.Aggregates.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
