// <auto-generated />
using System;
using IoBuild.Analytics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoBuild.Analytics.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260618184424_AddUnitFloorAndOwnerEmailProjections")]
    partial class AddUnitFloorAndOwnerEmailProjections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IoBuild.Analytics.Domain.Model.Entities.DeviceHealthStatus", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_online");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.ToTable("device_health_statuses", (string)null);
                });

            modelBuilder.Entity("IoBuild.Analytics.Domain.Model.Entities.HistoricalDataPoint", b =>
                {
                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metric");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.ToTable("historical_data_points", (string)null);
                });

            modelBuilder.Entity("IoBuild.Analytics.Domain.Model.Projections.DeviceProjection", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_type");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int")
                        .HasColumnName("floor_number");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_event_at");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("device_projections", (string)null);
                });

            modelBuilder.Entity("IoBuild.Analytics.Domain.Model.Projections.ProjectProjection", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("BuilderUserId")
                        .HasColumnType("int")
                        .HasColumnName("builder_user_id");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_event_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.HasKey("ProjectId");

                    b.HasIndex("BuilderUserId");

                    b.ToTable("project_projections", (string)null);
                });

            modelBuilder.Entity("IoBuild.Analytics.Domain.Model.Projections.UnitProjection", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<int>("BuilderUserId")
                        .HasColumnType("int")
                        .HasColumnName("builder_user_id");

                    b.Property<int?>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<DateTime>("LastEventAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_event_at");

                    b.Property<string>("OwnerEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("owner_email");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.HasKey("UnitId");

                    b.HasIndex("BuilderUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("unit_projections", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
